gsm/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('phoneBase/', include('phoneBase.urls', namespace='phoneBase')),
    path('admin/', admin.site.urls),
]

phoneBase/urls.py
from django.urls import path

from . import views

app_name = 'phoneBase'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('add/', views.phone_save, name='add_phone'),
    path('delete/<int:pk>', views.PhoneDelete.as_view(), name='phone_delete'),
    path('update/<int:pk>', views.PhoneUpdate.as_view(), name='phone_update'),
    path('<int:pk>/updateDetail', views.DetailsUpdate.as_view(), name='details_update'),

]

phoneBase/models.py
from django.db import models


# Create your models here.


class General(models.Model):
    producent = models.CharField(max_length=200, null=False, blank=False)
    typ = models.CharField(max_length=200, unique=True)


class Details(models.Model):
    general = models.ForeignKey(General, on_delete=models.CASCADE)
    procesor = models.CharField(max_length=200, default='Brak Informacji', null=False, blank=False)
    pamiec = models.CharField(max_length=200, default='Brak Informacji', null=False, blank=False)
    pamiec_ram = models.CharField(max_length=200, default='Brak Informacji', null=False, blank=False)
    bateria = models.CharField(max_length=200, default='Brak Informacji', null=False, blank=False)

    def __str__(self):
        return '{}{}{}{}'.format(self.procesor, self.pamiec, self.pamiec_ram, self.bateria)

phoneBase/forms.py
from django import forms

from .models import Details, General


class GeneralForm(forms.ModelForm):
    class Meta:
        model = General
        fields = "__all__"


class DetailForm(forms.ModelForm):
    class Meta:
        model = Details
        general = forms.ModelChoiceField(queryset=General.objects.all(), widget=forms.BaseModelFormSet, required=False)
        fields = ['procesor', 'pamiec', 'pamiec_ram', 'bateria']
        # fields = "__all__"

phoneBase/views.py
from django.shortcuts import render, redirect
from django.template.context_processors import csrf
from django.views import generic
from django.views.generic import DeleteView, UpdateView

from phoneBase.forms import DetailForm, GeneralForm
from .models import General, Details


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'phoneBase/index.html'
    context_object_name = 'phone_list'

    def get_queryset(self):
        return General.objects.all()


class DetailView(generic.DetailView):
    model = General
    template_name = 'phoneBase/details.html'


class PhoneDelete(DeleteView):
    model = General
    success_url = '/phoneBase/'


class PhoneUpdate(UpdateView):
    model = General
    fields = "__all__"
    success_url = '/phoneBase/'


class DetailsUpdate(UpdateView):
    model = Details
    fields = ['procesor', 'pamiec', 'pamiec_ram', 'bateria']
    success_url = '/phoneBase/'
    template_name = 'phoneBase/updateDetail.html'


def phone_save(request):
    if request.method == 'POST':
        general_form = GeneralForm(request.POST)
        details_form = DetailForm(request.POST)

        if general_form.is_valid() and details_form.is_valid():
            general = general_form.save()
            details = details_form.save(False)

            details.general = general
            details_form.full_clean()
            details.save()

            return redirect('/phoneBase/')
        else:
            return render(request, 'phoneBase/add.html', {'general_form': general_form, 'details_form': details_form},
                          {'error_message': "Coś poszło nie tak... spróbuj ponownie."})
    else:
        general_form = GeneralForm
        details_form = DetailForm
        args = {}
        args.update(csrf(request))
        args['general_form'] = general_form
        args['details_form'] = details_form

        return render(request, 'phoneBase/add.html', args)

phoneBase/templates/phoneBase/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>

<h1>Add phone form</h1>
<form method="POST">
    {% csrf_token %}

    {{general_form.as_p}}
    {{details_form.as_p}}
    <button type="submit">Save</button>
</form>
<a href="{% url 'phoneBase:index' %}">Strona glowna</a>
</body>
</html>

phoneBase/templates/phoneBase/details.html
<h1>{{ general.producent}} {{general.typ}}</h1>
<ul>
    {% for detail in general.details_set.all %}
    <li>{{ detail.procesor }}</li>
    <li>{{ detail.pamiec }}</li>
    <li>{{ detail.pamiec_ram }}</li>
    <li>{{ detail.bateria }}</li>
    {% endfor %}
</ul>
<a href="{% url 'phoneBase:details_update' general.id%}">Update</a>

phoneBase/templates/phoneBase/general_confirm_delete.html
<h1>Phone Delete?</h1>
<form  method="post">
{% csrf_token %}
Are you sure you want to delete this phone?
<input  type="submit"  value="Submit"  />
</form>

phoneBase/templates/phoneBase/general_form.html
<h1>General Update</h1>

<form  method="post">
{% csrf_token %}
{{ form.as_p }}
<input  type="submit"  value="Submit"  />
</form>

phoneBase/templates/phoneBase/index.html
{% if phone_list %}
<ul>
    {% for general in phone_list %}
    <li><a href="{% url 'phoneBase:detail' general.id %}">{{ general.producent }}</a>
        <a href="{% url 'phoneBase:phone_delete' general.id %}">Delete</a>
        <a href="{% url 'phoneBase:phone_update' general.id %}">Update</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
<a href="{% url 'phoneBase:add_phone' %}">Add a phone</a>

phoneBase/templates/phoneBase/updateDetail.html
<h1>General Update</h1>

<form  method="post">
{% csrf_token %}
{{ form.as_p }}
<input  type="submit"  value="Submit"  />
</form>